# Generated by Django 5.2.15 on 2026-07-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_id', models.CharField(max_length=32, unique=True)),
                ('building', models.CharField(max_length=255)),
                ('building_id', models.CharField(db_index=True, max_length=32)),
                ('account', models.CharField(max_length=255)),
                ('gap_type', models.CharField(choices=[('missing_utility_bill', 'Missing utility bill'), ('unmatched_meter', 'Unmatched meter'), ('incomplete_equipment_inventory', 'Incomplete equipment inventory'), ('tenant_owner_paid_ambiguity', 'Tenant/owner paid ambiguity')], max_length=64)),
                ('detail', models.TextField()),
                ('owner_role', models.CharField(choices=[('property_manager', 'Property manager'), ('asset_manager', 'Asset manager'), ('building_engineer', 'Building engineer')], max_length=32)),
                ('owner_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('drafted', 'Drafted'), ('approved', 'Approved'), ('sent', 'Sent'), ('resolved', 'Resolved')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
