# Generated by Django 5.2.15 on 2026-07-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedgap',
            name='draft',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trackedgap',
            name='groundedness_violations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trackedgap',
            name='is_grounded',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
